import { useEffect, useMemo, useState } from "react";
import { AlertCircle, BookOpenText, FileImage, FileText, GripVertical, ListTree, RefreshCw } from "lucide-react";

import { DashboardLayout } from "@/components/dashboard/dashboard-layout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { Language } from "@/lib/i18n";
import { cn } from "@/lib/utils";
import { articleRepository, type Article } from "@/repositories/articleRepository";
import { authorRepository, type Author } from "@/repositories/authorRepository";
import type { BookSection, BookSectionType } from "@/types/book-section";

const copy = {
  en: {
    eyebrow: "Book structure", title: "Book Layout", description: "Manage the structure and chapter order of the whole book.", chapters: "Chapters", sectionName: "Section name", type: "Type", sectionType: "Book Section", status: "Status", notImported: "Not imported", sectionDescription: "This area will be used to manage this section's content.", future: "Coming soon", futureFeatures: ["Online editing", "Import Word", "Import Markdown"], importChapter: "Import chapter (in development)", importToast: "This feature will be available in a future release. Supports Word, Markdown, and Text.", articlesCount: (count: number) => `${count} article${count === 1 ? "" : "s"} in this book`, articlesDescription: "Articles are arranged in the order they are approved.", articleFeatures: ["Drag to reorder", "Fixed sections", "Insert page breaks"], articleNumber: "No.", articleTitle: "Title", author: "Author", articleStatus: "Status", noArticles: "No main content yet.", noArticlesDescription: "Please wait for authors to submit and pass review.", preview: "Publication Preview", previewNote: "A full-page publishing preview will be generated from Layout, Template, and Articles.", previewTitle: "OpenClassBook", previewText: "Your book will take shape here.", loading: "Loading book content", errorTitle: "Unable to load book content.", errorDescription: "Please confirm that the backend is running.", reload: "Reload", statuses: { pending: "Pending", approved: "Approved", rejected: "Rejected" }, sections: { cover: "Cover", preface: "Preface", articles: "Author articles", afterword: "Afterword", acknowledgement: "Acknowledgements", back_cover: "Back cover" },
  },
  zh: {
    eyebrow: "书籍结构", title: "书籍排版", description: "管理整本书的结构与章节顺序。", chapters: "章节列表", sectionName: "章节名称", type: "类型", sectionType: "书籍章节", status: "状态", notImported: "未导入", sectionDescription: "这里将用于管理该章节的内容。", future: "即将推出", futureFeatures: ["在线编辑", "导入 Word", "导入 Markdown"], importChapter: "导入章节（开发中）", importToast: "该功能将在后续版本开放，届时将支持 Word、Markdown 和 Text。", articlesCount: (count: number) => `共 ${count} 篇文章`, articlesDescription: "文章将按照审核通过后的顺序排列。", articleFeatures: ["拖拽排序", "固定章节", "插入分页"], articleNumber: "编号", articleTitle: "标题", author: "作者", articleStatus: "状态", noArticles: "暂无正文内容。", noArticlesDescription: "请等待作者投稿并审核通过。", preview: "出版预览", previewNote: "后续将由 Layout、Template 和 Article 共同生成整页出版预览。", previewTitle: "OpenClassBook", previewText: "你的书籍将在这里成形。", loading: "正在加载书籍内容", errorTitle: "无法加载书籍内容。", errorDescription: "请确认后端正在运行。", reload: "重新加载", statuses: { pending: "待审核", approved: "已通过", rejected: "已退回" }, sections: { cover: "封面", preface: "前言", articles: "作者文章", afterword: "后记", acknowledgement: "致谢", back_cover: "封底" },
  },
} as const;

const sectionTypes: BookSectionType[] = ["cover", "preface", "articles", "afterword", "acknowledgement", "back_cover"];
const statusStyles = { draft: "border-border bg-muted/50 text-muted-foreground", pending: "border-amber-500/20 bg-amber-500/10 text-amber-400", approved: "border-emerald-500/20 bg-emerald-500/10 text-emerald-400", rejected: "border-rose-500/20 bg-rose-500/10 text-rose-400" };
interface BookLayoutPageProps { basePath: string; bookId: number; language: Language; onNavigate: (path: string) => void; onToggleLanguage: () => void; }
function getSections(bookId: number): BookSection[] { return sectionTypes.map((type, order) => ({ id: type, book_id: bookId, type, title: type, content: "", order })); }
function LayoutSkeleton({ language }: { language: Language }) { return <div aria-label={copy[language].loading} className="animate-pulse" role="status"><div className="h-8 w-48 rounded bg-muted" /><div className="mt-3 h-4 w-96 max-w-full rounded bg-muted/70" /><div className="mt-6 grid gap-5 xl:grid-cols-[260px_minmax(360px,0.9fr)_minmax(320px,0.8fr)]"><div className="h-[580px] rounded-xl border border-border bg-muted/30" /><div className="h-[580px] rounded-xl border border-border bg-muted/30" /><div className="h-[580px] rounded-xl border border-border bg-muted/30" /></div></div>; }

export function BookLayoutPage({ basePath, bookId, language, onNavigate, onToggleLanguage }: BookLayoutPageProps) {
  const pageCopy = copy[language]; const [articles, setArticles] = useState<Article[]>([]); const [authors, setAuthors] = useState<Author[]>([]); const [selectedType, setSelectedType] = useState<BookSectionType>("cover"); const [isLoading, setIsLoading] = useState(true); const [hasError, setHasError] = useState(false); const [reloadKey, setReloadKey] = useState(0); const [notice, setNotice] = useState<string | null>(null);
  useEffect(() => { let active = true; setIsLoading(true); setHasError(false); Promise.all([articleRepository.listByBook(bookId), authorRepository.listByBook(bookId)]).then(([loadedArticles, loadedAuthors]) => { if (active) { setArticles(loadedArticles); setAuthors(loadedAuthors); } }).catch(() => active && setHasError(true)).finally(() => active && setIsLoading(false)); return () => { active = false; }; }, [bookId, reloadKey]);
  const sections = useMemo(() => getSections(bookId), [bookId]); const selectedSection = sections.find((section) => section.type === selectedType) ?? sections[0]; const approvedArticles = useMemo(() => articles.filter((article) => article.review_status === "approved"), [articles]); const authorNames = useMemo(() => new Map(authors.map((author) => [author.id, author.name])), [authors]); const shellProps = { activeSection: "Layout" as const, basePath, language, onNavigate, onToggleLanguage };
  if (isLoading) return <DashboardLayout {...shellProps}><LayoutSkeleton language={language} /></DashboardLayout>;
  if (hasError) return <DashboardLayout {...shellProps}><div className="mx-auto mt-20 max-w-lg rounded-xl border border-border bg-card px-7 py-12 text-center"><AlertCircle className="mx-auto size-5 text-rose-400" /><h1 className="mt-5 text-lg font-semibold text-foreground">{pageCopy.errorTitle}</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">{pageCopy.errorDescription}</p><Button className="mt-6 h-9 rounded-lg px-4 text-xs" onClick={() => setReloadKey((value) => value + 1)} type="button"><RefreshCw className="mr-2 size-3.5" />{pageCopy.reload}</Button></div></DashboardLayout>;
  const showImportNotice = () => { setNotice(pageCopy.importToast); window.setTimeout(() => setNotice(null), 4000); };
  return <DashboardLayout {...shellProps}><header className="border-b border-border pb-7"><p className="mb-2 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.16em] text-blue-400"><ListTree className="size-3.5" />{pageCopy.eyebrow}</p><h1 className="text-2xl font-semibold tracking-[-0.035em] text-foreground sm:text-3xl">{pageCopy.title}</h1><p className="mt-2 text-sm text-muted-foreground">{pageCopy.description}</p></header><div className="mt-6 grid items-start gap-5 xl:grid-cols-[260px_minmax(360px,0.9fr)_minmax(320px,0.8fr)]"><aside className="overflow-hidden rounded-xl border border-border bg-card xl:sticky xl:top-24 xl:flex xl:h-[calc(100vh-7.5rem)] xl:flex-col"><div className="border-b border-border px-4 py-3 text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">{pageCopy.chapters}</div><div className="min-h-0 flex-1 p-2">{sections.map((section) => { const articleSection = section.type === "articles"; const Icon = section.type === "cover" || section.type === "back_cover" ? FileImage : articleSection ? BookOpenText : FileText; return <button className={cn("mb-1 flex w-full items-center gap-3 rounded-lg border px-3 py-3 text-left transition-colors", selectedType === section.type ? "border-blue-500/25 bg-blue-500/[0.08]" : "border-transparent hover:bg-muted/50")} key={section.id} onClick={() => setSelectedType(section.type)} type="button"><GripVertical className="size-3.5 text-muted-foreground/50" /><Icon className="size-4 text-blue-400" /><span className="flex-1 text-sm font-medium text-foreground">{pageCopy.sections[section.type]}{articleSection ? ` (${approvedArticles.length})` : ""}</span></button>; })}</div></aside><section className="overflow-hidden rounded-xl border border-border bg-card xl:sticky xl:top-24 xl:flex xl:h-[calc(100vh-7.5rem)] xl:flex-col">{selectedSection.type === "articles" ? <ArticleSection articles={approvedArticles} authorNames={authorNames} basePath={basePath} copy={pageCopy} language={language} onNavigate={onNavigate} /> : <SectionDetails copy={pageCopy} onImport={showImportNotice} section={selectedSection} />}</section><PublicationPreview copy={pageCopy} /></div>{notice ? <div aria-live="polite" className="fixed bottom-5 right-5 z-50 max-w-sm rounded-lg border border-blue-500/20 bg-card px-4 py-3 text-sm text-foreground shadow-xl" role="status">{notice}</div> : null}</DashboardLayout>;
}
function SectionDetails({ copy: pageCopy, onImport, section }: { copy: (typeof copy)[Language]; onImport: () => void; section: BookSection }) { return <div className="flex min-h-[500px] flex-col p-5 sm:p-6"><dl className="space-y-5"><div><dt className="text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">{pageCopy.sectionName}</dt><dd className="mt-2 text-xl font-semibold text-foreground">{pageCopy.sections[section.type]}</dd></div><div className="grid grid-cols-2 gap-4 border-y border-border py-5"><div><dt className="text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">{pageCopy.type}</dt><dd className="mt-2 text-sm text-foreground">{pageCopy.sectionType}</dd></div><div><dt className="text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">{pageCopy.status}</dt><dd className="mt-2"><Badge className="border border-border bg-muted/50 text-muted-foreground">{pageCopy.notImported}</Badge></dd></div></div></dl><div className="mt-6 flex-1"><p className="text-sm text-muted-foreground">{pageCopy.sectionDescription}</p><p className="mt-6 text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">{pageCopy.future}</p><ul className="mt-3 space-y-2 text-sm text-muted-foreground">{pageCopy.futureFeatures.map((feature) => <li key={feature}>• {feature}</li>)}</ul></div><Button aria-disabled="true" className="h-10 cursor-not-allowed rounded-lg opacity-50" onClick={onImport} type="button">{pageCopy.importChapter}</Button></div>; }
function ArticleSection({ articles, authorNames, basePath, copy: pageCopy, language, onNavigate }: { articles: Article[]; authorNames: Map<number, string>; basePath: string; copy: (typeof copy)[Language]; language: Language; onNavigate: (path: string) => void }) { return <div className="flex min-h-[500px] flex-col"><div className="border-b border-border p-5 sm:p-6"><h2 className="text-xl font-semibold text-foreground">{pageCopy.articlesCount(articles.length)}</h2><p className="mt-2 text-sm text-muted-foreground">{pageCopy.articlesDescription}</p><ul className="mt-5 flex flex-wrap gap-x-4 gap-y-2 text-xs text-muted-foreground">{pageCopy.articleFeatures.map((feature) => <li key={feature}>• {feature}</li>)}</ul></div>{articles.length ? <div className="min-h-0 flex-1 overflow-y-auto"><div className="grid grid-cols-[52px_minmax(0,1fr)_auto] gap-3 border-b border-border px-5 py-3 text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground"><span>{pageCopy.articleNumber}</span><span>{pageCopy.articleTitle}</span><span>{pageCopy.articleStatus}</span></div>{articles.map((article) => <button className="grid w-full grid-cols-[52px_minmax(0,1fr)_auto] gap-3 border-b border-border px-5 py-4 text-left transition-colors hover:bg-muted/50" key={article.id} onClick={() => onNavigate(`${basePath}/review`)} type="button"><span className="font-mono text-xs text-muted-foreground">{article.number}</span><span className="min-w-0"><span className="block truncate text-sm font-medium text-foreground">{article.title}</span><span className="mt-1 block truncate text-xs text-muted-foreground">{pageCopy.author}: {authorNames.get(article.author_id) ?? `${language === "zh" ? "作者" : "Author"} #${article.author_id}`}</span></span><Badge className={cn("h-fit border text-[9px] uppercase", statusStyles[article.review_status])}>{pageCopy.statuses[article.review_status]}</Badge></button>)}</div> : <div className="flex flex-1 flex-col items-center justify-center px-6 py-16 text-center"><BookOpenText className="size-5 text-muted-foreground" /><h2 className="mt-4 text-sm font-semibold text-foreground">{pageCopy.noArticles}</h2><p className="mt-1.5 max-w-xs text-sm text-muted-foreground">{pageCopy.noArticlesDescription}</p></div>}</div>; }
function PublicationPreview({ copy: pageCopy }: { copy: (typeof copy)[Language] }) { return <aside className="overflow-hidden rounded-xl border border-border bg-card shadow-xl xl:sticky xl:top-24"><header className="flex h-12 items-center gap-2 border-b border-border px-4"><span className="size-1.5 rounded-full bg-emerald-400" /><h2 className="text-xs font-semibold text-foreground">{pageCopy.preview}</h2></header><div className="flex min-h-[500px] items-center justify-center bg-muted/40 p-6 sm:p-10"><article className="flex aspect-[148/210] w-full max-w-[340px] flex-col justify-between bg-[#fffefa] p-9 text-slate-800 shadow-[0_20px_70px_rgba(0,0,0,0.42)]"><div><p className="text-[10px] font-semibold uppercase tracking-[0.24em] text-slate-400">Publication preview</p><div className="mt-12 h-px w-12 bg-slate-300" /><h3 className="mt-5 text-3xl font-semibold tracking-[-0.04em]">{pageCopy.previewTitle}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{pageCopy.previewText}</p></div><p className="text-xs text-slate-400">01</p></article></div><p className="border-t border-border px-4 py-3 text-xs leading-5 text-muted-foreground">{pageCopy.previewNote}</p></aside>; }
